# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adicionarConfRegional.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AdicionarConfDlg(object):
    def setupUi(self, AdicionarConfDlg):
        AdicionarConfDlg.setObjectName("AdicionarConfDlg")
        AdicionarConfDlg.resize(541, 528)
        self.widget = QtWidgets.QWidget(AdicionarConfDlg)
        self.widget.setGeometry(QtCore.QRect(30, 12, 484, 494))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.novaRegiaoLineEdit = QtWidgets.QLineEdit(self.widget)
        self.novaRegiaoLineEdit.setObjectName("novaRegiaoLineEdit")
        self.horizontalLayout_6.addWidget(self.novaRegiaoLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.naoInclusosLista = QtWidgets.QListWidget(self.widget)
        self.naoInclusosLista.setMinimumSize(QtCore.QSize(51, 31))
        self.naoInclusosLista.setMaximumSize(QtCore.QSize(51, 91))
        self.naoInclusosLista.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.naoInclusosLista.setObjectName("naoInclusosLista")
        self.horizontalLayout.addWidget(self.naoInclusosLista)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(23, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.includeToolButton = QtWidgets.QToolButton(self.widget)
        self.includeToolButton.setArrowType(QtCore.Qt.RightArrow)
        self.includeToolButton.setObjectName("includeToolButton")
        self.verticalLayout.addWidget(self.includeToolButton)
        self.removeToolButton = QtWidgets.QToolButton(self.widget)
        self.removeToolButton.setArrowType(QtCore.Qt.LeftArrow)
        self.removeToolButton.setObjectName("removeToolButton")
        self.verticalLayout.addWidget(self.removeToolButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.inclusosLista = QtWidgets.QListWidget(self.widget)
        self.inclusosLista.setMinimumSize(QtCore.QSize(51, 31))
        self.inclusosLista.setMaximumSize(QtCore.QSize(51, 91))
        self.inclusosLista.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.inclusosLista.setObjectName("inclusosLista")
        self.horizontalLayout.addWidget(self.inclusosLista)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(191, 141))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 152, 94))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.soloSpinBox3 = QtWidgets.QSpinBox(self.layoutWidget)
        self.soloSpinBox3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soloSpinBox3.setPrefix("")
        self.soloSpinBox3.setMaximum(300)
        self.soloSpinBox3.setSingleStep(5)
        self.soloSpinBox3.setProperty("value", 10)
        self.soloSpinBox3.setObjectName("soloSpinBox3")
        self.gridLayout_3.addWidget(self.soloSpinBox3, 2, 1, 1, 1)
        self.soloSpinBox1 = QtWidgets.QSpinBox(self.layoutWidget)
        self.soloSpinBox1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soloSpinBox1.setPrefix("")
        self.soloSpinBox1.setMaximum(300)
        self.soloSpinBox1.setSingleStep(5)
        self.soloSpinBox1.setProperty("value", 10)
        self.soloSpinBox1.setObjectName("soloSpinBox1")
        self.gridLayout_3.addWidget(self.soloSpinBox1, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.soloSpinBox2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.soloSpinBox2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soloSpinBox2.setPrefix("")
        self.soloSpinBox2.setMaximum(300)
        self.soloSpinBox2.setSingleStep(5)
        self.soloSpinBox2.setProperty("value", 10)
        self.soloSpinBox2.setObjectName("soloSpinBox2")
        self.gridLayout_3.addWidget(self.soloSpinBox2, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.tipoVradComboBox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tipoVradComboBox.sizePolicy().hasHeightForWidth())
        self.tipoVradComboBox.setSizePolicy(sizePolicy)
        self.tipoVradComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.tipoVradComboBox.setObjectName("tipoVradComboBox")
        self.horizontalLayout_2.addWidget(self.tipoVradComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gruposLista = QtWidgets.QListWidget(self.widget)
        self.gruposLista.setMaximumSize(QtCore.QSize(101, 81))
        self.gruposLista.setObjectName("gruposLista")
        self.horizontalLayout_7.addWidget(self.gruposLista)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.adicionarGrupoButton = QtWidgets.QPushButton(self.widget)
        self.adicionarGrupoButton.setMaximumSize(QtCore.QSize(21, 21))
        self.adicionarGrupoButton.setObjectName("adicionarGrupoButton")
        self.verticalLayout_3.addWidget(self.adicionarGrupoButton)
        self.removerGrupoButton = QtWidgets.QPushButton(self.widget)
        self.removerGrupoButton.setMaximumSize(QtCore.QSize(21, 21))
        self.removerGrupoButton.setObjectName("removerGrupoButton")
        self.verticalLayout_3.addWidget(self.removerGrupoButton)
        self.editarGrupoButton = QtWidgets.QPushButton(self.widget)
        self.editarGrupoButton.setMaximumSize(QtCore.QSize(21, 21))
        self.editarGrupoButton.setObjectName("editarGrupoButton")
        self.verticalLayout_3.addWidget(self.editarGrupoButton)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        spacerItem6 = QtWidgets.QSpacerItem(36, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(AdicionarConfDlg)
        self.buttonBox.rejected.connect(AdicionarConfDlg.reject)
        self.buttonBox.accepted.connect(AdicionarConfDlg.accept)
        self.naoInclusosLista.itemDoubleClicked['QListWidgetItem*'].connect(self.includeToolButton.click)
        self.inclusosLista.itemDoubleClicked['QListWidgetItem*'].connect(self.removeToolButton.click)
        self.gruposLista.itemDoubleClicked['QListWidgetItem*'].connect(self.editarGrupoButton.click)
        QtCore.QMetaObject.connectSlotsByName(AdicionarConfDlg)
        AdicionarConfDlg.setTabOrder(self.novaRegiaoLineEdit, self.soloSpinBox1)
        AdicionarConfDlg.setTabOrder(self.soloSpinBox1, self.soloSpinBox2)
        AdicionarConfDlg.setTabOrder(self.soloSpinBox2, self.soloSpinBox3)
        AdicionarConfDlg.setTabOrder(self.soloSpinBox3, self.removeToolButton)
        AdicionarConfDlg.setTabOrder(self.removeToolButton, self.inclusosLista)
        AdicionarConfDlg.setTabOrder(self.inclusosLista, self.includeToolButton)
        AdicionarConfDlg.setTabOrder(self.includeToolButton, self.naoInclusosLista)
        AdicionarConfDlg.setTabOrder(self.naoInclusosLista, self.buttonBox)
        AdicionarConfDlg.setTabOrder(self.buttonBox, self.tipoVradComboBox)
        AdicionarConfDlg.setTabOrder(self.tipoVradComboBox, self.gruposLista)
        AdicionarConfDlg.setTabOrder(self.gruposLista, self.adicionarGrupoButton)
        AdicionarConfDlg.setTabOrder(self.adicionarGrupoButton, self.removerGrupoButton)
        AdicionarConfDlg.setTabOrder(self.removerGrupoButton, self.editarGrupoButton)

    def retranslateUi(self, AdicionarConfDlg):
        _translate = QtCore.QCoreApplication.translate
        AdicionarConfDlg.setWindowTitle(_translate("AdicionarConfDlg", "Adicionar Configuração Regional"))
        self.label_11.setText(_translate("AdicionarConfDlg", "Configuração Regional"))
        self.label_7.setText(_translate("AdicionarConfDlg", "Estados"))
        self.includeToolButton.setText(_translate("AdicionarConfDlg", "..."))
        self.removeToolButton.setText(_translate("AdicionarConfDlg", "..."))
        self.groupBox.setTitle(_translate("AdicionarConfDlg", "Reserva Útil de Água"))
        self.label_10.setText(_translate("AdicionarConfDlg", "Solo Tipo 3"))
        self.soloSpinBox3.setSuffix(_translate("AdicionarConfDlg", " mm"))
        self.soloSpinBox1.setSuffix(_translate("AdicionarConfDlg", " mm"))
        self.label_9.setText(_translate("AdicionarConfDlg", "Solo Tipo 2"))
        self.soloSpinBox2.setSuffix(_translate("AdicionarConfDlg", " mm"))
        self.label_8.setText(_translate("AdicionarConfDlg", "Solo Tipo 1"))
        self.label_6.setText(_translate("AdicionarConfDlg", "Tipo Velocidade Radicular"))
        self.label.setText(_translate("AdicionarConfDlg", "Grupos"))
        self.adicionarGrupoButton.setText(_translate("AdicionarConfDlg", "+"))
        self.removerGrupoButton.setText(_translate("AdicionarConfDlg", "-"))
        self.editarGrupoButton.setText(_translate("AdicionarConfDlg", "..."))

