# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adicionargrupo.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_adicionarGrupoDlg(object):
    def setupUi(self, adicionarGrupoDlg):
        adicionarGrupoDlg.setObjectName("adicionarGrupoDlg")
        adicionarGrupoDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        adicionarGrupoDlg.resize(619, 515)
        self.layoutWidget = QtWidgets.QWidget(adicionarGrupoDlg)
        self.layoutWidget.setGeometry(QtCore.QRect(16, 21, 583, 465))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.grupoLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.grupoLineEdit.setObjectName("grupoLineEdit")
        self.horizontalLayout_4.addWidget(self.grupoLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.duracaoCicloLabel = QtWidgets.QLabel(self.layoutWidget)
        self.duracaoCicloLabel.setObjectName("duracaoCicloLabel")
        self.horizontalLayout_7.addWidget(self.duracaoCicloLabel)
        spacerItem1 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.duracaoTableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duracaoTableWidget.sizePolicy().hasHeightForWidth())
        self.duracaoTableWidget.setSizePolicy(sizePolicy)
        self.duracaoTableWidget.setMinimumSize(QtCore.QSize(351, 0))
        self.duracaoTableWidget.setMaximumSize(QtCore.QSize(16777215, 61))
        self.duracaoTableWidget.setRowCount(1)
        self.duracaoTableWidget.setColumnCount(10)
        self.duracaoTableWidget.setObjectName("duracaoTableWidget")
        self.duracaoTableWidget.horizontalHeader().setDefaultSectionSize(35)
        self.duracaoTableWidget.horizontalHeader().setHighlightSections(True)
        self.duracaoTableWidget.horizontalHeader().setMinimumSectionSize(4)
        self.duracaoTableWidget.verticalHeader().setVisible(False)
        self.duracaoTableWidget.verticalHeader().setDefaultSectionSize(25)
        self.horizontalLayout.addWidget(self.duracaoTableWidget)
        spacerItem2 = QtWidgets.QSpacerItem(34, 14, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem3 = QtWidgets.QSpacerItem(23, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(571, 161))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 40, 524, 104))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.tipoKcComboBox = QtWidgets.QComboBox(self.layoutWidget_3)
        self.tipoKcComboBox.setObjectName("tipoKcComboBox")
        self.gridLayout_2.addWidget(self.tipoKcComboBox, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 2, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 3, 2, 1)
        self.kcTableWidget = QtWidgets.QTableWidget(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kcTableWidget.sizePolicy().hasHeightForWidth())
        self.kcTableWidget.setSizePolicy(sizePolicy)
        self.kcTableWidget.setMinimumSize(QtCore.QSize(351, 0))
        self.kcTableWidget.setMaximumSize(QtCore.QSize(16777215, 61))
        self.kcTableWidget.setRowCount(1)
        self.kcTableWidget.setColumnCount(10)
        self.kcTableWidget.setObjectName("kcTableWidget")
        self.kcTableWidget.horizontalHeader().setDefaultSectionSize(35)
        self.kcTableWidget.horizontalHeader().setHighlightSections(True)
        self.kcTableWidget.horizontalHeader().setMinimumSectionSize(4)
        self.kcTableWidget.verticalHeader().setVisible(False)
        self.kcTableWidget.verticalHeader().setDefaultSectionSize(25)
        self.gridLayout_2.addWidget(self.kcTableWidget, 1, 1, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem6 = QtWidgets.QSpacerItem(23, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setMinimumSize(QtCore.QSize(484, 32))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(adicionarGrupoDlg)
        self.buttonBox.accepted.connect(adicionarGrupoDlg.accept)
        self.buttonBox.rejected.connect(adicionarGrupoDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(adicionarGrupoDlg)

    def retranslateUi(self, adicionarGrupoDlg):
        _translate = QtCore.QCoreApplication.translate
        adicionarGrupoDlg.setWindowTitle(_translate("adicionarGrupoDlg", "Adicionar Grupo"))
        self.label.setText(_translate("adicionarGrupoDlg", "Grupo"))
        self.label_4.setText(_translate("adicionarGrupoDlg", "Duração do ciclo"))
        self.duracaoCicloLabel.setText(_translate("adicionarGrupoDlg", "0 dias"))
        self.label_6.setText(_translate("adicionarGrupoDlg", "Duração das Fases"))
        self.groupBox.setTitle(_translate("adicionarGrupoDlg", "Coeficientes Culturais"))
        self.label_3.setText(_translate("adicionarGrupoDlg", "Tipo"))
        self.label_5.setText(_translate("adicionarGrupoDlg", "Valores Decendiais"))

